name: Build and Release Executable

on:
  push:
    tags:
      - "v*.*.*"  # Runs only when you push a version tag (e.g., v1.0.0)
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

permissions:  # ✅ Gives proper GitHub permissions for releases
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest  # Only runs on Linux

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Nuitka
        run: pip install nuitka

      - name: Install Dependencies
        run: sudo apt-get install -y gcc g++

      - name: Build Executable
        run: |
          nuitka --standalone --onefile main.py
          mv main.bin lifpm

      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-executables
          path: lifpm

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')  # Only run on tag pushes
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"  # ✅ Fixed: 'release_name' → 'name'
          body: "🚀 Automatically generated release for ${{ github.ref_name }}."
          files: lifpm
